apiVersion: v1
kind: Service
metadata:
  name: labswork-svc1
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: labswork
  type: ClusterIP  
---
apiVersion: v1
kind: Service
metadata:
  name: labswork-svc2
spec:
  type: NodePort
  ports:
    - port: 8082
      protocol: TCP
      targetPort: 8080
  selector:
    app: labswork

# kubectl apply -f app-service.yaml 