apiVersion: apps/v1
kind: Deployment
metadata:
  name: labswork
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labswork
  template:
    metadata:
      labels:
        app: labswork
    spec:
      containers:
      - name: labswork
        image: giantconiku/labs-devops:latest
        env:
          - name: DATABASE_URL
            value: flora.db.elephantsql.com/goqiiclc
          - name: DATABASE_USERNAME
            value: goqiiclc
          - name: DATABASE_PASSWORD
            value: Ph9h-RloqaKXArOIX4_RucN4WMws0-1Z
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: logs-volume
            mountPath: /var/logs
      volumes:
        - name: logs-volume
          persistentVolumeClaim:
            claimName: labs-logs-pvc

# kubectl apply -f app-deployment.yaml 