apiVersion: v1
kind: PersistentVolume
metadata:
  name: labs-logs-pv
  labels:
    type: local
    app: labswork
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/logs"
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labs-logs-pvc
  labels:
    app: labswork
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
  volumeName: labs-logs-pv
  